# Generated by Django 4.2.3 on 2023-07-16 15:48

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BannerAera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BannerImage', models.ImageField(upload_to='media/Banner_images')),
                ('Discount_Deal', models.CharField(choices=[('On Sale', 'On Sale'), ('Hot Sale', 'Hot Sale'), ('Hot Deals', 'Hot Deals'), ('New Arrivals', 'New Arrivals')], max_length=40, null=True)),
                ('Title', models.CharField(max_length=100)),
                ('Discount', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Name', models.CharField(max_length=200)),
                ('Total_Quantity', models.IntegerField()),
                ('Available', models.IntegerField()),
                ('Product_Image', models.CharField(max_length=500)),
                ('Price', models.CharField(max_length=10)),
                ('Discount', models.CharField(max_length=8)),
                ('Product_Info', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('Model_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Tags', models.CharField(max_length=100)),
                ('Product_Desc', ckeditor.fields.RichTextField()),
                ('slug', models.SlugField(blank=True, default='', max_length=1000, null=True)),
                ('Product_Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='XMarket.category')),
            ],
            options={
                'db_table': 'XMarket_Product',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SliderImage', models.ImageField(upload_to='media/slider_images')),
                ('Discount_Deal', models.CharField(choices=[('On Sale', 'On Sale'), ('Hot Sale', 'Hot Sale'), ('Hot Deals', 'Hot Deals'), ('New Arrivals', 'New Arrivals')], max_length=40, null=True)),
                ('Sale', models.IntegerField()),
                ('Brand_Name', models.CharField(max_length=100)),
                ('Discount', models.IntegerField(blank=True, null=True)),
                ('Slider_link', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('dob', models.DateField(blank=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('number', models.PositiveIntegerField()),
                ('is_superuser', models.BooleanField(default=False, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='XMarket.category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image_Url', models.CharField(max_length=1000)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='XMarket.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='Product_Section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='XMarket.section'),
        ),
        migrations.AddField(
            model_name='category',
            name='mainCategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='XMarket.maincategory'),
        ),
        migrations.CreateModel(
            name='Additional_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specifications', models.CharField(max_length=500)),
                ('details', models.CharField(max_length=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='XMarket.product')),
            ],
        ),
    ]
