# Generated by Django 4.2.3 on 2023-07-25 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XMarket', '0008_brand_product_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='packing_cost',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='tax',
            field=models.IntegerField(null=True),
        ),
    ]
