# Generated by Django 4.2.3 on 2023-07-26 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XMarket', '0010_coupon_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon_code',
            name='Expired',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
