# Generated by Django 4.2.3 on 2023-07-27 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XMarket', '0011_coupon_code_expired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='packing_cost',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
